export const items = [
  {
    id: 1,
    name: "Manzana",
    type: "fruta",
    price: 2,
    emoji: "🍎",
    caducidad: "2025-03-10",
    enOferta: true,
  },
  {
    id: 2,
    name: "Plátano",
    type: "fruta",
    price: 1,
    emoji: "🍌",
    caducidad: "2025-02-28",
    enOferta: false,
  },
  {
    id: 3,
    name: "Zanahoria",
    type: "verdura",
    price: 1.5,
    emoji: "🥕",
    caducidad: "2025-03-15",
    enOferta: true,
  },
  {
    id: 4,
    name: "Lechuga",
    type: "verdura",
    price: 1,
    emoji: "🥬",
    caducidad: "2025-02-25",
    enOferta: false,
  },
  {
    id: 5,
    name: "Fresas",
    type: "fruta",
    price: 3,
    emoji: "🍓",
    caducidad: "2025-02-20",
    enOferta: true,
  },
];
